language: dart

dart:
  - dev
  - stable

# See https://docs.travis-ci.com/user/languages/dart/ for details.
dart_task:
  - test: --platform vm
    xvfb: false
  - test: --platform firefox
    install_dartium: true
  - dartanalyzer

matrix:
  include:
    - dart: stable
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
