name: glob
version: 1.1.2
author: "Dart Team <misc@dartlang.org>"
homepage: https://github.com/dart-lang/glob
description: Bash-style filename globbing.
dependencies:
  async: "^1.2.0"
  collection: ">=1.1.0 <2.0.0"
  path: ">=1.3.0 <2.0.0"
  string_scanner: ">=0.1.0 <0.2.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  scheduled_test: ">=0.12.0 <0.13.0"
environment:
  sdk: ">=1.12.0 <2.0.0"
